stages:
  - build
  - deployment-development
  - update_portainer_qa
  - update_portainer_uat

master_build:
  stage: build
  variables:
    REGISTRY_ADDRESS: 'registry.dnamicro.com'
    REGISTRY_USERNAME: 'dev'
    REGISTRY_PASSWORD: 'F0nch3rt0'
  script:
    - 'docker login $REGISTRY_ADDRESS -u $REGISTRY_USERNAME -p $REGISTRY_PASSWORD'
    - "docker build -t $REGISTRY_ADDRESS/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME-$CI_PIPELINE_ID -f dockerfile \
      --build-arg PROJECT=$CI_PROJECT_NAME ."
    - 'docker tag $REGISTRY_ADDRESS/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME-$CI_PIPELINE_ID $REGISTRY_ADDRESS/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME'
    - 'docker push $REGISTRY_ADDRESS/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME-$CI_PIPELINE_ID'
    - 'docker push $REGISTRY_ADDRESS/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME'
  only:
    - 'development'
    - 'qa'
    - 'uat'

update_stack:
  stage: deployment-development
  variables:
    ENDPOINT_ID: 2
    STACK_ID: 120
    PORTAINER_USERNAME: 'admin'
    PORTAINER_PASSWORD: 'tLs&uG3p2L?rIvl'
    PORTAINER_HOST: https://portainer.development.dnadev.net
    PORTAINER_YML_FILE: application.yml
    PORTAINER_ENV_FILE: application.env
    REGISTRY_ADDRESS: 'registry.dnamicro.com'
    FILE_PATH: /var/apps/portainer
  script:
    - PORTAINER_HOST=$PORTAINER_HOST portainer login -u $PORTAINER_USERNAME -p $PORTAINER_PASSWORD
    - cd  $FILE_PATH && rm -rf  $PORTAINER_YML_FILE && PORTAINER_HOST=$PORTAINER_HOST portainer stackfile $STACK_ID $PORTAINER_YML_FILE
    - cd  $FILE_PATH && sed -i "s/${CI_PROJECT_NAME}:.*/${CI_PROJECT_NAME}:${CI_COMMIT_REF_NAME}-${CI_PIPELINE_ID}/g" $PORTAINER_YML_FILE
    - echo 'updating contract-template-fn'
    - cd  $FILE_PATH && PORTAINER_HOST=$PORTAINER_HOST portainer stack:update  $ENDPOINT_ID  $STACK_ID  $PORTAINER_YML_FILE -e $PORTAINER_ENV_FILE
  only:
    - 'development'

#========================= QA ==========================#
update_portainer_qa:
  only:
    - qa
  script:
    # - docker login $REGISTRY_ADDRESS -u $REGISTRY_USERNAME -p $REGISTRY_PASSWORD
    # - docker pull $REGISTRY_ADDRESS/$CI_PROJECT_NAME:$BASE_REF_NAME
    # - docker tag $REGISTRY_ADDRESS/$CI_PROJECT_NAME:$BASE_REF_NAME $REGISTRY_ADDRESS/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME-$CI_PIPELINE_ID
    # - docker tag $REGISTRY_ADDRESS/$CI_PROJECT_NAME:$BASE_REF_NAME $REGISTRY_ADDRESS/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME
    # - docker push $REGISTRY_ADDRESS/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME-$CI_PIPELINE_ID
    # - docker push $REGISTRY_ADDRESS/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME

    - PORTAINER_HOST=$PORTAINER_HOST portainer login -u $PORTAINER_USERNAME -p $PORTAINER_PASSWORD
    - touch $FILE_PATH/$PORTAINER_YML_FILE
    - rm -rf $FILE_PATH/$PORTAINER_YML_FILE && PORTAINER_HOST=$PORTAINER_HOST portainer stackfile $STACK_ID $FILE_PATH/$PORTAINER_YML_FILE
    - sed -r -i "s/${CI_PROJECT_NAME}:${CI_COMMIT_REF_NAME}-[0-9]+/${CI_PROJECT_NAME}:${CI_COMMIT_REF_NAME}-${CI_PIPELINE_ID}/g" $FILE_PATH/$PORTAINER_YML_FILE
    - echo 'updating contract-template-fn'
    - cat $FILE_PATH/$PORTAINER_YML_FILE
    - PORTAINER_HOST=$PORTAINER_HOST portainer stack:update $ENDPOINT_ID $STACK_ID $FILE_PATH/$PORTAINER_YML_FILE -e $FILE_PATH/$PORTAINER_ENV_FILE
  stage: update_portainer_qa
  variables:
    BASE_REF_NAME: development
    ENDPOINT_ID: 2
    STACK_ID: 29
    FILE_PATH: /var/apps/portainer
    PORTAINER_ENV_FILE: qa-application.env
    PORTAINER_YML_FILE: qa-application.yml
    PORTAINER_HOST: https://portainer.qa.mygo.gorentals.com
    PORTAINER_PASSWORD: 'n3RhuaVDeSgRMV'
    PORTAINER_USERNAME: 'admin'
    REGISTRY_ADDRESS: registry.dnamicro.com
    REGISTRY_PASSWORD: F0nch3rt0
    REGISTRY_USERNAME: dev

#===================== UAT =======================#
update_portainer_uat:
  stage: update_portainer_uat
  variables:
    ENDPOINT_ID: 2
    STACK_ID: 23
    PORTAINER_HOST: https://portainer.uat.mygo.gorentals.com
    PORTAINER_PASSWORD: '94SL@^mfNm#xZgF9MePuexN&PCdaS@uT'
    PORTAINER_USERNAME: 'ci'
    PORTAINER_ENV_FILE: mygo-uat-application-api.env
    PORTAINER_YML_FILE: mygo-uat-application-api.yml
    REGISTRY_ADDRESS: 'registry.dnamicro.com'
    REGISTRY_USERNAME: 'dev'
    REGISTRY_PASSWORD: 'F0nch3rt0'
    FILE_PATH: /var/apps/portainer
    BASE_REF_NAME: 'qa'
  script:
    #=================================== Docker Operations ========================================#
    # - docker login $REGISTRY_ADDRESS -u $REGISTRY_USERNAME -p $REGISTRY_PASSWORD
    # - docker pull $REGISTRY_ADDRESS/$CI_PROJECT_NAME:$BASE_REF_NAME
    # - docker tag $REGISTRY_ADDRESS/$CI_PROJECT_NAME:$BASE_REF_NAME $REGISTRY_ADDRESS/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME-$CI_PIPELINE_ID
    # - docker tag $REGISTRY_ADDRESS/$CI_PROJECT_NAME:$BASE_REF_NAME $REGISTRY_ADDRESS/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME
    # - docker push $REGISTRY_ADDRESS/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME-$CI_PIPELINE_ID
    # - docker push $REGISTRY_ADDRESS/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME
    #=================================== Update Portainer Operations ========================================#
    - PORTAINER_HOST=$PORTAINER_HOST portainer login -u $PORTAINER_USERNAME -p $PORTAINER_PASSWORD
    - touch $FILE_PATH/$PORTAINER_YML_FILE
    - rm -rf $FILE_PATH/$PORTAINER_YML_FILE && PORTAINER_HOST=$PORTAINER_HOST portainer stackfile $STACK_ID $FILE_PATH/$PORTAINER_YML_FILE
    - sed -r -i "s/${CI_PROJECT_NAME}:${CI_COMMIT_REF_NAME}-[0-9]+/${CI_PROJECT_NAME}:${CI_COMMIT_REF_NAME}-${CI_PIPELINE_ID}/g" $FILE_PATH/$PORTAINER_YML_FILE
    - echo 'updating Events-API'
    - cat $FILE_PATH/$PORTAINER_YML_FILE
    - PORTAINER_HOST=$PORTAINER_HOST portainer stack:update $ENDPOINT_ID $STACK_ID $FILE_PATH/$PORTAINER_YML_FILE -e $FILE_PATH/$PORTAINER_ENV_FILE
  only:
    - 'uat'
